### ISSUE TITLE
Issue about the dataset annotation.

### ISSUE THREAD

**Issue by HarborYuan** [VIPSeg-Dataset/VIPSeg-Dataset#1]
Hi, @sssdddwww2 

Thanks for your work on the vipseg dataset.

I am using your datasets on my own project, but I found a annotation problem.

In the 
```
VIPSeg/imgs/353_-5sqmCF8OFU/00000392.jpg (img)
VIPSeg/panomasks/353_-5sqmCF8OFU/00000392.png (annotation)
```

I found that there is a "200" in the annotation file. According to the rules, 200 means that the mask belongs to a thing class and its id is 1 (200 // OFFSET - 1). However, in the category file, id = 1 refers to "ceiling" class and of course it is a stuff class.

I am wondering whether there are bugs like this in the datasets or whether I understand something wrong.

Thanks agian.

**Comment by VIPSeg-Dataset** [comment]
hi @HarborYuan , it is a bug in the dataset. I checked the folder of 353_-5sqmCF8OFU and where "200" is should be "0". Thanks for pointing out it.

**Comment by HarborYuan** [comment]
Ok, thanks for your help.
