### ISSUE TITLE
Where are change2_720p.py, create_panoptic_video_labels.py and splitjson.py?

### ISSUE THREAD

**Issue by leaf1170124460** [VIPSeg-Dataset/VIPSeg-Dataset#2]
Hi, @VIPSeg-Dataset and @sssdddwww2 .
Thanks for your work on the VIPSeg dataset.

I want to use your datasets on my project, but I found a problem.

In readme, change VIPSeg to 720P and COCO format need to use `change2_720p.py`, `create_panoptic_video_labels.py` and `splitjson.py`, but I can not find them in this project. Could you please tell me where to find them?

### Change VIPSeg to 720P and COCO Format

```
pip install git+https://github.com/cocodataset/panopticapi.git

python change2_720p.py

python create_panoptic_video_labels.py

python splitjson.py
```

**Comment by VIPSeg-Dataset** [comment]
@leaf1170124460 Download the VIPSeg dataset via Google Drive or Baidu YunPan, and the files are with the dataset.

**Comment by leaf1170124460** [comment]
Thank you very much for your reply! 👍👍👍
Because the dataset is large, so the download time is long, and there is no way to see the contents of the dataset until the download is complete. Perhaps you could add a note in readme stating that these three files are in the dataset? So that the user knows where these files are before the download is complete.

**Comment by XavierCHEN34** [comment]
I download the dataset but could not find the create_panoptic_video_labels.py and splitjson.py, could you add them into the master-branch?
