### ISSUE TITLE
A problem about eval_stq_vspw.py

### ISSUE THREAD

**Issue by leaf1170124460** [VIPSeg-Dataset/VIPSeg-Dataset#4]
Hi, @VIPSeg-Dataset and @sssdddwww2  .
Thanks for your work on the VIPSeg dataset.

I want to use your evaluation codes, but I am confused about some codes.

In `eval_stq_vspw.py`, lines from 167 to 171, why does prediction use `pan_gt == id_` rather than `pan_pred == id_`? 
```
for el in pred_json['segments_info']:
    id_ = el['id']
    cate_id = el['category_id']
    prediction_semantic[pan_gt==id_] = cate_id
    prediction_instance[pan_gt==id_] = pred_id_to_ins_num_dic[id_]
```

**Comment by VIPSeg-Dataset** [comment]
@leaf1170124460 I checked it and it seems to be a mistake. Thank you so much to point out it.  I have updated the code. Thanks.
