### ISSUE TITLE
Regarding VPQ performance

### ISSUE THREAD

**Issue by dlsrbgg33** [VIPSeg-Dataset/VIPSeg-Dataset#6]
Hi, 
Thank you for your great work.

When I evaluated  the 'model_final.pth' for inference, I obtained quite a higher score than the paper suggested. Below is the number that I obtained with the provided run_val.sh

VPQ1: 27.2 / VPQ2: 25.9 / VPQ4: 24.1 /  VPQ6: 22.8 / VPQ8: 22.1 
VPQall: 24.99

Could you guide me where this score comes from?

**Comment by VIPSeg-Dataset** [comment]
Hi, the results reported in the paper used "clip length=8" for better STQ score. Using shorter clip length (2 or 3) can get higher VPQ score than the reported one.

**Comment by dlsrbgg33** [comment]
Thank you!
