### ISSUE TITLE
Regarding VPQ window span

### ISSUE THREAD

**Issue by dlsrbgg33** [VIPSeg-Dataset/VIPSeg-Dataset#7]
According to the [code](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/blob/5177fe879a0dd7c335a9b02927a60efe9c1e4854/ClipPanoFCN/eval_vpq_vspw.py#L390), the VPQ window span is [1,2,4,6,8]. However, I thought that [1,2,4,6] is the standard window span as shown in your paper.
Could you clarify which window span do I have to follow for VPQ evaluation?

**Comment by VIPSeg-Dataset** [comment]
[1,2,4,6] is used for VPQ evaluation. In the code we used the VPQ window span of 8 and it is extremely time-consuming. Thus we only report the results of  [1,2,4,6] in our paper.

**Comment by dlsrbgg33** [comment]
Thank you for the reply!
